In [34]:
import numpy as np
import pandas as pd
import warnings

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

warnings.filterwarnings("ignore")
print(np.__version__)
print(pd.__version__)

2.5.2
3.0.5

In [35]:
df = pd.read_csv("Walmart_Sales.csv")
print(df)

      Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  12-02-2010    1641957.44             1        38.51       2.548
2         1  19-02-2010    1611968.17             0        39.93       2.514
3         1  26-02-2010    1409727.59             0        46.63       2.561
4         1  05-03-2010    1554806.68             0        46.50       2.625
...     ...         ...           ...           ...          ...         ...
6430     45  28-09-2012     713173.95             0        64.88       3.997
6431     45  05-10-2012     733455.07             0        64.89       3.985
6432     45  12-10-2012     734464.36             0        54.47       4.000
6433     45  19-10-2012     718125.53             0        56.47       3.969
6434     45  26-10-2012     760281.43             0        58.85       3.882

             CPI  Unemployment
0     211.096358         8.106
1     211.242170         8.106
2     211.289143         8.106
3     211.319643         8.106
4     211.350143         8.106
...          ...           ...
6430  192.013558         8.684
6431  192.170412         8.667
6432  192.327265         8.667
6433  192.330854         8.667
6434  192.308899         8.667

[6435 rows x 8 columns]

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   str
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), str(1)
memory usage: 402.3 KB

In [37]:
df.shape

(6435, 8)

In [38]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [39]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='str')

In [40]:
df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

In [41]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df_label = df.copy()
df_label['Date'].head()

0    05-02-2010
1    12-02-2010
2    19-02-2010
3    26-02-2010
4    05-03-2010
Name: Date, dtype: str

In [44]:
df_label['Date'] = pd.to_datetime(df_label['Date'],format="%d-%m-%Y")
df_label.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106

In [45]:
df_label['Date'].dtype

dtype('<M8[us]')

In [46]:
df_label['Year']=df_label['Date'].dt.year
df_label['Months']=df_label['Date'].dt.month
df_label['Week']=df_label['Date'].dt.isocalendar().week
print(df_label)

      Store       Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1 2010-02-05    1643690.90             0        42.31       2.572
1         1 2010-02-12    1641957.44             1        38.51       2.548
2         1 2010-02-19    1611968.17             0        39.93       2.514
3         1 2010-02-26    1409727.59             0        46.63       2.561
4         1 2010-03-05    1554806.68             0        46.50       2.625
...     ...        ...           ...           ...          ...         ...
6430     45 2012-09-28     713173.95             0        64.88       3.997
6431     45 2012-10-05     733455.07             0        64.89       3.985
6432     45 2012-10-12     734464.36             0        54.47       4.000
6433     45 2012-10-19     718125.53             0        56.47       3.969
6434     45 2012-10-26     760281.43             0        58.85       3.882

             CPI  Unemployment  Year  Months  Week
0     211.096358         8.106  2010       2     5
1     211.242170         8.106  2010       2     6
2     211.289143         8.106  2010       2     7
3     211.319643         8.106  2010       2     8
4     211.350143         8.106  2010       3     9
...          ...           ...   ...     ...   ...
6430  192.013558         8.684  2012       9    39
6431  192.170412         8.667  2012      10    40
6432  192.327265         8.667  2012      10    41
6433  192.330854         8.667  2012      10    42
6434  192.308899         8.667  2012      10    43

[6435 rows x 11 columns]

In [47]:
X = df_label.drop(['Weekly_Sales', 'Date'], axis=1)
y = df_label['Weekly_Sales']

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5148, 9)
(1287, 9)
(5148,)
(1287,)

In [51]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
print("Model Trained Successfully")

Model Trained Successfully

In [52]:
y_pred = model.predict(X_test)
print(y_pred[:5])
print(y_test.head())

[1162156.92272994 1090740.12562435 1300301.65727919 1196000.80331717
  695835.03147633]
2436    1138800.32
3361    1304850.67
233     1769296.25
3667    1077640.13
5011     428851.99
Name: Weekly_Sales, dtype: float64

In [59]:
print(y_test.head())

2436    1138800.32
3361    1304850.67
233     1769296.25
3667    1077640.13
5011     428851.99
Name: Weekly_Sales, dtype: float64

In [54]:
print("Predicted:")
print(y_pred[:10])

print("\nActual:")
print(y_test.head(10).values)

Predicted:
[1162156.92272994 1090740.12562435 1300301.65727919 1196000.80331717
  695835.03147633  919478.49465652  951218.17981528 1199586.92989139
  990842.56712156 1219441.98206256]

Actual:
[1138800.32 1304850.67 1769296.25 1077640.13  428851.99 1004523.59
 1523410.71 1014898.78 1955896.59  958667.23]

In [61]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
print(mse)
print(mae)
print(rmse)
print(r2)

272049348139.45172
432594.9768878015
521583.5006395924
0.15553160499602903